# 异常断言日志

## 异常分类

异常对象都是派生于Throwable

 只应该抛出检查型异常.

## 创建异常类

```java
package com.catcherror.note;

import java.io.IOException;

/*
 * @Author 不灵不落我是个机器人 .
 * @Email: rzc307853639@gmail.com .
 * @Date time: 2020/10/09/8:20 PM .
 * @Description .
 */
public class FileFormatException extends IOException {
  public FileFormatException() {}

  public FileFormatException(final String a) {
    super(a);
  }
}

class ErrorTest {
  public static String readData(final int length) throws FileFormatException {
    if (length < 1) {
      throw new FileFormatException();
    }
    System.out.println("congratulations!");
    return "congratulations!";
  }

  public static void main(final String[] args) throws FileFormatException {
    ErrorTest.readData(2);
  }
}

```

## 捕获异常

如果try语句中的任意代码抛出了catch语句中指定的一个异常类,那么

1. 程序将会跳过try语句的其他代码
2. 程序将会执行catch块中的代码

```java
  public static void main(final String[] args) {
    try {
      ErrorTest.readData(0);
    } catch (final FileFormatException e) {
      System.out.println("在" + e.toString() + "抛出了异常");
    }
  }
```

如果没有抛出,那么将跳过catch语句

## 处理方式

一般有两种,一种是捕获,一种是将异常传递给调用者

```java
  public static void main(final String[] args) throws FileFormatException {
    ErrorTest.readData(2);
  }
  public static void main(final String[] args) {
    try {
      ErrorTest.readData(0);
    } catch (final FileFormatException e) {
      System.out.println("在" + e.toString() + "抛出了异常");
    }
  }
```

如果调用了一个抛出检查型异常的方法,那么你就必须处理这个异常,或者继续传递异常

**一般经验是处理你知道如何处理异常,传播你不知道如何处理的异常**